[build]
command = "echo 'no op'"
publish = "example"

[build.environment]
NODE_VERSION = "16.15.1"

[[plugins]]
package = "netlify-plugin-cypress"
# do not run tests after deploy
[plugins.inputs]
enable = false
# run tests after build
[plugins.inputs.postBuild]
enable = true
